Refactor D2Common ordinal 10515 for easier flow
ThePhrozenKeep/D2MOO pull request #77
Opened 2022-11-27 12:20 UTC by IAmTrial

These changes simplify ordinal 10515 for better readability.

For documentation reference: This function appears to be a free/dealloc function for D2UnitStrc starting from a StatList marked STATLIST_TEMPONLY.

2022-11-27 19:04 UTC, Lectem requested changes
This function seems to remove any temporary effects. It disable the current states and removes stats if they are not linked to the unit (not StatListEx).
Could be named `STATLIST_DisableTemporaryStats`, `STATLIST_DeactivateTemporaryStates` or something along those lines.

Note that it is called in D2Common.`UNITS_ChangeAnimMode` when anim mode changes, or in D2Client.0x6FB42D40 when velocity percentage (stat = 67) changes.

2022-11-27 20:20 UTC, IAmTrial commented
After reading your comments, I took a look at the function again. I realized that my understanding of the removal was incorrect. It does not remove all the stats after the temporary one, but only that specific stat.

2022-11-27 20:39 UTC, merged

2022-11-27 20:44 UTC, Lectem commented
Realized right after merging there was an issue (pPrevious was assigned twice). Fixed in commit https://github.com/ThePhrozenKeep/D2MOO/commit/16f75a8fbc3e0a3f019a08cb809bbe45dfaa6afe

2022-11-28 10:41 UTC, Necrolis commented
IMO if you are going to refactor, you might want to also improve readability; in this case prefer early returns instead of scope nesting:
```cpp
	if (pUnit->pStatListEx && pUnit->pStatListEx->dwFlags & STATLIST_NEWLENGTH)
	{
//...
        }
```
becomes
```cpp
	if (pUnit->pStatListEx == nullptr || !(pUnit->pStatListEx->dwFlags & STATLIST_NEWLENGTH)) {
	    return;
        }
```